// C++ Classes, Abstract Interfaces, and Templates Demo (C++17)
// Mirrors the Rust structs_traits_generics demo.
//
// Sections:
//   1 — Classes: data and behavior together; access specifiers
//   2 — Abstract base class as interface (pure virtual methods)
//   3 — Multiple inheritance and composition (the C++ way)
//   4 — Templates: duck typing, checked at instantiation
//   5 — Virtual (dynamic) dispatch vs template (static) dispatch

#include <algorithm>
#include <cassert>
#include <cmath>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

// ─────────────────────────────────────────────────────────────────────────────
// Section 1 — Classes
// ─────────────────────────────────────────────────────────────────────────────

// C++ class: data AND behavior defined together in one block.
// Access specifiers: public, protected, private (default: private for class, public for struct).
//
// Rust equivalent:
//   struct Rectangle { width: f64, height: f64 }   ← data only
//   impl Rectangle { fn new(...) -> Self {...} }    ← behavior separate
class Rectangle {
public:
    // Constructor — Rust equivalent: associated fn new()
    Rectangle(double width, double height)
        : width_(width), height_(height)
    {
        assert(width > 0 && height > 0 && "dimensions must be positive");
    }

    // const methods (immutable) — Rust: &self methods
    double area()      const { return width_ * height_; }
    double perimeter() const { return 2.0 * (width_ + height_); }
    bool   is_square() const { return std::abs(width_ - height_) < 1e-10; }

    // non-const method (mutable) — Rust: &mut self method
    void scale(double factor) {
        width_  *= factor;
        height_ *= factor;
    }

    // Move-semantic method: invalidates *this after call (convention only — C++ can't enforce)
    // Rust: fn into_square(self) -> Rectangle  — compiler enforces the original is gone
    Rectangle into_square() const {
        double side = std::min(width_, height_);
        return Rectangle(side, side);
    }

    double width()  const { return width_; }
    double height() const { return height_; }

    // Copy constructor generated by compiler (Rust: #[derive(Clone)])
    // operator== must be written manually unless C++20 `= default`
    bool operator==(const Rectangle& o) const {
        return width_ == o.width_ && height_ == o.height_;
    }

    // Stream output — Rust equivalent: impl fmt::Display for Rectangle
    friend std::ostream& operator<<(std::ostream& os, const Rectangle& r) {
        return os << "Rectangle(" << r.width_ << "x" << r.height_ << ")";
    }

private:
    double width_;    // private fields — Rust fields are also private by default
    double height_;
};

static void section1_classes() {
    std::cout << "=== Section 1: Classes ===\n";
    std::cout << "C++ class: data AND behavior defined TOGETHER in one block.\n";
    std::cout << "Rust struct: DATA ONLY; behavior in a separate impl block.\n\n";

    Rectangle r1(10.0, 5.0);
    std::cout << "  r1 = " << r1 << "\n";
    std::cout << "  area     = " << r1.area() << "\n";
    std::cout << "  perimeter= " << r1.perimeter() << "\n";
    std::cout << "  is_square= " << std::boolalpha << r1.is_square() << "\n";

    // Copy (Rust: clone())
    Rectangle r3 = r1;   // copy constructor — implicit in C++
    std::cout << "\n  r3 (copy of r1) = " << r3 << "\n";
    std::cout << "  r1 == r3: " << (r1 == r3) << "\n";

    // Mutable method
    Rectangle r4(3.0, 4.0);
    std::cout << "\n  r4 before scale: " << r4 << "\n";
    r4.scale(2.0);
    std::cout << "  r4 after scale(2.0): " << r4 << "\n";

    // into_square: C++ can't prevent r4 from being used after this (Rust can)
    Rectangle sq = r4.into_square();
    std::cout << "  sq = " << sq << "  is_square=" << sq.is_square() << "\n";

    std::cout << "\n  KEY DIFFERENCES from Rust structs:\n";
    std::cout << "    C++ struct vs class: only default access differs (public vs private)\n";
    std::cout << "    C++: copy constructor / operator= auto-generated (or written manually)\n";
    std::cout << "    Rust: #[derive(Clone, PartialEq, Debug)] generates equivalents\n";
    std::cout << "    C++: no field-init shorthand; no struct update syntax\n";
    std::cout << "    Rust: let r2 = Rectangle { width: 20.0, ..r1 };  (update syntax)\n";
    std::cout << "    Rust: impl block can be anywhere, even another file\n\n";
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 2 — Abstract Base Class as Interface
// ─────────────────────────────────────────────────────────────────────────────

// C++ "interface" = abstract base class with pure virtual methods.
// Rust equivalent: trait Shape { fn area(&self) -> f64; ... }
//
// KEY DIFFERENCES:
//   - C++ requires inheritance at the point of class definition.
//   - Rust: impl Shape for Rectangle lives outside both definitions.
//   - C++: virtual destructor required to avoid UB on polymorphic delete.
//   - Rust: Drop trait handles cleanup; no virtual destructor needed.
//   - C++: "default method" = virtual with a body (non-pure virtual).
//   - Rust: default methods in the trait body — no override keyword.

class Shape {
public:
    virtual ~Shape() = default;               // virtual destructor — REQUIRED in C++

    virtual double area()      const = 0;     // pure virtual — Rust: required fn
    virtual double perimeter() const = 0;     // pure virtual
    virtual std::string name() const = 0;     // pure virtual

    // Non-pure virtual = default method — Rust: default fn in trait body
    virtual std::string describe() const {
        std::ostringstream oss;
        oss << name() << ": area=" << area() << ", perimeter=" << perimeter();
        return oss.str();
    }

    // Default method that calls other virtuals
    bool is_larger_than(const Shape& other) const {
        return area() > other.area();
    }
};

// Inheritance — C++ way to implement an interface
// Rust: impl Shape for Rectangle { ... }  — NO inheritance keyword
class RectangleShape : public Rectangle, public Shape {
public:
    RectangleShape(double w, double h) : Rectangle(w, h) {}

    double area()      const override { return Rectangle::area(); }
    double perimeter() const override { return Rectangle::perimeter(); }
    std::string name() const override { return "Rectangle"; }
    // describe() uses the default from Shape — same as Rust default method
};

class Circle : public Shape {
public:
    explicit Circle(double radius) : radius_(radius) {}

    double area()      const override { return M_PI * radius_ * radius_; }
    double perimeter() const override { return 2.0 * M_PI * radius_; }
    std::string name() const override { return "Circle"; }

    // Override the default describe — Rust: just provide the method in impl block
    std::string describe() const override {
        std::ostringstream oss;
        oss << "Circle with radius=" << radius_ << " (area=" << area() << ")";
        return oss.str();
    }

    double radius() const { return radius_; }

private:
    double radius_;
};

class Triangle : public Shape {
public:
    Triangle(double a, double b, double c) : a_(a), b_(b), c_(c) {
        assert(a + b > c && b + c > a && a + c > b);
    }

    double area() const override {
        double s = perimeter() / 2.0;
        return std::sqrt(s * (s-a_) * (s-b_) * (s-c_));
    }
    double perimeter() const override { return a_ + b_ + c_; }
    std::string name() const override { return "Triangle"; }

private:
    double a_, b_, c_;
};

static void section2_abstract_interface() {
    std::cout << "=== Section 2: Abstract Base Class as Interface ===\n";
    std::cout << "C++: abstract class with pure virtual methods.\n";
    std::cout << "Rust: trait with required method signatures.\n\n";
    std::cout << "  KEY DIFFERENCES from Rust traits:\n";
    std::cout << "    C++: class RectangleShape : public Shape — inheritance at definition\n";
    std::cout << "    Rust: impl Shape for Rectangle — independent, anywhere in code\n";
    std::cout << "    C++: must write virtual ~Shape() = default (virtual destructor)\n";
    std::cout << "    Rust: no destructor management needed\n";
    std::cout << "    C++: no mechanism to impl Shape for types you don't control\n";
    std::cout << "    Rust: can impl a trait for foreign types (orphan rule permitting)\n\n";

    RectangleShape rect(6.0, 4.0);
    Circle         circ(3.0);
    Triangle       tri(3.0, 4.0, 5.0);

    std::cout << "  describe() — default vs overridden:\n";
    std::cout << "    rect: " << rect.describe() << "\n";  // default
    std::cout << "    circ: " << circ.describe() << "\n";  // overridden
    std::cout << "    tri:  " << tri.describe()  << "\n";  // default

    std::cout << "\n  is_larger_than() — non-pure virtual default:\n";
    std::cout << "    rect.is_larger_than(circ): " << std::boolalpha
              << rect.is_larger_than(circ) << "\n";
    std::cout << "    circ.is_larger_than(tri):  "
              << circ.is_larger_than(tri) << "\n\n";
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 3 — Multiple Inheritance and Composition
// ─────────────────────────────────────────────────────────────────────────────

class Drawable {
public:
    virtual ~Drawable() = default;
    virtual void draw() const = 0;
};

class Resizable {
public:
    virtual ~Resizable() = default;
    virtual void resize(double factor) = 0;
};

// Multiple inheritance — C++ allows it, but the diamond problem lurks
class DrawableRect : public RectangleShape, public Drawable, public Resizable {
public:
    DrawableRect(double w, double h) : RectangleShape(w, h) {}

    void draw() const override {
        std::cout << "    [drawing rectangle " << width() << "x" << height() << "]\n";
    }
    void resize(double factor) override { scale(factor); }
};

// Composition — preferred in both C++ and Rust to avoid diamond problems
// Rust: struct ColoredShape<S: Shape + Drawable> { shape: S, color: String }
template <typename S>  // S must be a Shape and Drawable
class ColoredShape {
public:
    ColoredShape(S shape, std::string color)
        : shape_(std::move(shape)), color_(std::move(color)) {}

    void draw_colored() const {
        std::cout << "    color=" << color_ << " ";
        shape_.draw();
    }
    double area()      const { return shape_.area(); }
    double perimeter() const { return shape_.perimeter(); }

private:
    S           shape_;
    std::string color_;
};

static void section3_composition() {
    std::cout << "=== Section 3: Multiple Inheritance and Composition ===\n";
    std::cout << "C++: multiple inheritance (diamond problem possible).\n";
    std::cout << "Rust: multiple trait impls + composition (no diamond problem).\n\n";

    DrawableRect dr(4.0, 3.0);
    std::cout << "  DrawableRect implements Shape + Drawable + Resizable:\n";
    std::cout << "    area=" << dr.area() << "  perimeter=" << dr.perimeter() << "\n";
    dr.draw();
    dr.resize(2.0);
    std::cout << "    after resize(2.0): area=" << dr.area() << "\n";

    std::cout << "\n  Composition — ColoredShape<DrawableRect>:\n";
    ColoredShape<DrawableRect> colored(DrawableRect(5.0, 2.0), "red");
    colored.draw_colored();
    std::cout << "    area (delegated): " << colored.area() << "\n";

    std::cout << "\n  Diamond problem:\n";
    std::cout << "    C++: class D : public B, public C where B and C both derive A\n";
    std::cout << "         causes ambiguity; need virtual inheritance to resolve.\n";
    std::cout << "    Rust: no state in traits — diamond problem cannot occur.\n";
    std::cout << "          If two traits define the same method, you qualify explicitly:\n";
    std::cout << "          Trait1::method(&x)  or  Trait2::method(&x)\n\n";
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 4 — Templates
// ─────────────────────────────────────────────────────────────────────────────

// C++ template: UNCONSTRAINED by default — errors appear at instantiation.
// C++17: no constraint syntax; rely on SFINAE or static_assert.
// C++20: concepts provide compile-time bounds (closest to Rust trait bounds).

// C++17 unconstrained template — Rust equivalent: fn largest<T: PartialOrd>
// Error only if T doesn't support > — at CALL SITE, not here
template <typename T>
const T& largest(const std::vector<T>& list) {
    assert(!list.empty());
    const T* biggest = &list[0];
    for (const T& item : list) {
        if (item > *biggest) biggest = &item;
    }
    return *biggest;
}

// Generic struct — Rust: struct Pair<T, U> { first: T, second: U }
template <typename T, typename U>
struct Pair {
    T first;
    U second;

    Pair(T f, U s) : first(std::move(f)), second(std::move(s)) {}

    // Conditional method: available only when T and U are comparable and printable.
    // C++17: use if constexpr or SFINAE. C++20: use requires.
    // Rust: impl<T, U> Pair<T, U> where T: Display + PartialOrd, U: Display + PartialOrd
    void cmp_display() const {
        std::cout << "    first=" << first
                  << (first >= second ? " >= " : " < ")
                  << "second=" << second << "\n";
    }
};

// C++17 template function with multiple concept-like constraints via static_assert
// Rust: fn print_shape_info<T: Shape + Debug>(shape: &T)
template <typename T>
void print_shape_info(const T& shape) {
    // In C++17 there's no compile-time guarantee T has .name()/.area()
    // — errors only if T doesn't have those methods, at instantiation
    std::cout << "    " << shape.name() << " → area=" << shape.area() << "\n";
}

static void section4_templates() {
    std::cout << "=== Section 4: Templates ===\n";
    std::cout << "C++ template: unconstrained duck typing; errors at INSTANTIATION.\n";
    std::cout << "Rust generic: trait-bounded; errors at DEFINITION.\n\n";

    std::vector<int>         ints    = {34, 50, 25, 100, 65};
    std::vector<double>      doubles = {7.2, 4.5, 9.1, 3.3};
    std::vector<std::string> words   = {"apple", "orange", "banana", "cherry"};

    std::cout << "  largest() — same template, three instantiations:\n";
    std::cout << "    largest(ints)    = " << largest(ints)    << "\n";
    std::cout << "    largest(doubles) = " << largest(doubles) << "\n";
    std::cout << "    largest(words)   = " << largest(words)   << "\n\n";

    std::cout << "  Generic struct Pair<T, U>:\n";
    Pair<int, int>               p1(10, 20);
    Pair<std::string, std::string> p2("hello", "world");
    Pair<double, double>         p3(1.5, 0.5);
    p1.cmp_display();
    p2.cmp_display();
    p3.cmp_display();

    std::cout << "\n  print_shape_info<T>(shape):\n";
    RectangleShape r(3.0, 4.0);
    Circle         c(2.0);
    Triangle       t(3.0, 4.0, 5.0);
    print_shape_info(r);
    print_shape_info(c);
    print_shape_info(t);

    std::cout << "\n  KEY DIFFERENCES from Rust generics:\n";
    std::cout << "    C++17: template<typename T> — no bounds; duck typing\n";
    std::cout << "           error message if T lacks needed method: at call site (cryptic)\n";
    std::cout << "    C++20: template<typename T> requires std::totally_ordered<T>\n";
    std::cout << "           concept = closer to Rust trait bound\n";
    std::cout << "    Rust:  fn f<T: Trait>(x: T) — error if bound not met: at definition\n";
    std::cout << "           (clear, predictable error messages)\n";
    std::cout << "    Both:  monomorphization at compile time — zero runtime overhead\n\n";
}

// ─────────────────────────────────────────────────────────────────────────────
// Section 5 — Virtual (Dynamic) vs Template (Static) Dispatch
// ─────────────────────────────────────────────────────────────────────────────

// Template (static) dispatch — Rust: fn f<T: Shape>(shapes: &[T])
// Compiler instantiates a separate function per T. Zero vtable overhead.
template <typename T>
double total_area_static(const std::vector<T>& shapes) {
    double total = 0.0;
    for (const T& s : shapes) total += s.area();
    return total;
}

// Virtual (dynamic) dispatch — Rust: fn f(shapes: &[Box<dyn Shape>])
// Each call goes through the vtable. Required for heterogeneous collections.
static double total_area_dynamic(const std::vector<std::unique_ptr<Shape>>& shapes) {
    double total = 0.0;
    for (const auto& s : shapes) total += s->area();
    return total;
}

static void print_all(const std::vector<std::unique_ptr<Shape>>& shapes) {
    for (const auto& s : shapes) {
        std::cout << "    " << s->describe() << "\n";
    }
}

static void section5_dispatch() {
    std::cout << "=== Section 5: Static Dispatch vs Dynamic (Virtual) Dispatch ===\n\n";

    // Static dispatch via templates
    std::cout << "  Static dispatch — template instantiation per type:\n";
    std::cout << "    Compiler generates a separate total_area_static for each T.\n";
    std::cout << "    Zero runtime overhead — identical to Rust static dispatch.\n\n";

    std::vector<Circle> circles = { Circle(1.0), Circle(2.0), Circle(3.0) };
    std::cout << "    total_area_static([Circle×3]) = "
              << total_area_static(circles) << "\n";

    // Dynamic dispatch via virtual
    std::cout << "\n  Dynamic dispatch — vtable pointer per object:\n";
    std::cout << "    Every virtual call = one pointer dereference (vtable lookup).\n";
    std::cout << "    Rust: &dyn Shape / Box<dyn Shape> — same mechanism, explicit opt-in.\n";
    std::cout << "    C++: ALL virtual calls are dynamic — no way to opt for static.\n";
    std::cout << "    Required for mixing different concrete types in one collection.\n\n";

    std::vector<std::unique_ptr<Shape>> shapes;
    shapes.push_back(std::make_unique<RectangleShape>(3.0, 4.0));
    shapes.push_back(std::make_unique<Circle>(2.0));
    shapes.push_back(std::make_unique<Triangle>(3.0, 4.0, 5.0));

    print_all(shapes);
    std::cout << "    total_area_dynamic (mixed vec) = "
              << total_area_dynamic(shapes) << "\n";

    std::cout << "\n  Summary — static vs dynamic dispatch:\n";
    std::cout << "    C++   static:  template<T> — no vtable, inlinable, T must be uniform\n";
    std::cout << "    C++   dynamic: virtual     — vtable, heterogeneous collections OK\n";
    std::cout << "    Rust  static:  <T: Trait>  — no vtable, inlinable (default choice)\n";
    std::cout << "    Rust  dynamic: dyn Trait   — vtable, explicit, heterogeneous OK\n";
    std::cout << "    Rust forces you to consciously choose; C++ virtual is always dynamic.\n";
}

// ─────────────────────────────────────────────────────────────────────────────

int main() {
    section1_classes();
    section2_abstract_interface();
    section3_composition();
    section4_templates();
    section5_dispatch();
    return 0;
}
