[package]
name = "ownership_demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ownership_demo"
path = "src/main.rs"

[[bin]]
name = "memory_demo"
path = "src/bin/memory_demo.rs"

[[bin]]
name = "lifetime_demo"
path = "src/bin/lifetime_demo.rs"

[[bin]]
name = "structs_traits_generics"
path = "src/bin/structs_traits_generics.rs"

[[bin]]
name = "closures_demo"
path = "src/bin/closures_demo.rs"

[[bin]]
name = "iterators_demo"
path = "src/bin/iterators_demo.rs"

[[bin]]
name = "error_handling"
path = "src/bin/error_handling.rs"

[[bin]]
name = "concurrency_demo"
path = "src/bin/concurrency_demo.rs"

[[bin]]
name = "macros_demo"
path = "src/bin/macros_demo.rs"

[dependencies]
proc_macros = { path = "proc_macros" }
